name: Build and Release TaskMate APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Release APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Generate Release Tag
        id: tag
        run: |
          echo "release_tag=v$(date +'%Y.%m.%d_%H-%M')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: TaskMate ${{ steps.tag.outputs.release_tag }}
          files: build/app/outputs/flutter-apk/app-release.apk
          body: |
            TaskMate Release
            
            ## Features
            - Task Management (Add, Edit, Delete)
            - Dark/Light Theme
            - Category-based organization
            - Search functionality
            - Responsive design
            
            ## Installation
            1. Download the APK
            2. Install on your Android device
            3. Allow installation from unknown sources if prompted
            
            Build Date: ${{ steps.tag.outputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk 